spring:
  datasource:
    url: jdbc:h2:mem:bestchoice
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
#      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 799378242531-6sdsso0a2asq5ui7h3it5gruhfekpr2o.apps.googleusercontent.com
            client-secret: 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
            redirect-uri:  http://localhost:8080/oauth2/callback/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          naver:
            client-id: AG0HCsAdTPX7aLTg66gE
            client-secret: 6zLGjhXepX
            authorization-grant-type:
            client-name:
            redirect-uri:
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            client-authentication-method: POST
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
          naver:
            authorization-uri: https://nid.naver.com/auth2.0/authorize
            jwk-set-uri: https://openapi.naver.com/v1/nid/verify
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: reponse
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  profiles:
    include: oauth

app:
  oauth2:
    authorizedRedirectUri: http://localhost:3000/oauth2/redirect

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  issuer: zerowinnow23@gmail.com
  secret_key : winnow-bestchoice-secretkey