spring:
  datasource:
    url: jdbc:h2:mem:bestchoice
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxxxxxxxxxx
            client-secret: xxxxxxxxxxxxxxxxxxxxxx
            redirect-uri: http://localhost:8080/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
  profiles:
    include: oauth

logging:
    level:
      org.springframework.security: DEBUG


# jwt issuer, secret key 설정
jwt:
  issuer: zerowinnow23@gmail.com
  secret_key: 'winnow-bestchoice-secretkey'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenExpiry: 1800000 # 30분
    refreshTokenExpiry: 604800000 # 7일
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

# cors 설정
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600